### ISSUE TITLE
SDK Patching support to build system

### ISSUE THREAD

**Issue by jrosberg** [ruuvi/ruuvitag_fw#1]
At the moment SDK requires some patching to compile example fw correctly:

`ERROR: ...........\components\libraries\bootloader_dfu\dfu_app_handler.c(153): error: #136: struct "" has no field "BOOTLOADERADDR".`

You have to modify line 146 and 153 in components\libraries\bootloader_dfu\dfu_app_handler.c. In both those lines you should replace NRF_UICR->BOOTLOADERADDR with *(uint32_t *)(0x10001014). 
https://devzone.nordicsemi.com/question/56723/dfu-on-nrf52/

**Comment by laurijamsa** [comment]
Patched!
