### ISSUE TITLE
init_blink_status must always return

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvitag_fw#102]
main calls `drivers/init/init.c init_blink_status `after initializing each of the subsystems which - if an error has occurred - hangs with 

```
while(init_status);
    nrf_gpio_pin_set(LED_RED);
```
Although this is desirable for factory QA it is unacceptable for deployed tags which have been know to spontaneously reset.

Suggested change: On error stall for 10 seconds with red LED blinking  with 2:1 (on:off) duty cycle  to inform factory QA that a failure has occurred, 
then return to main.

**Comment by ojousima** [comment]
I'll take this on my TODO, estimated to be completed in March 2018

**Comment by DG12** [comment]
I'd like to take this on.

**Comment by ojousima** [comment]
Thank you @DG12 for offering to help with this. Can you also take a look at #99 while you're at it?
Do you have a Ruuvi devkit already?

Please keep the error code as OR'ed, because the error codes will have a more precise meaning such as "device not found on bus" or "device self-test failed"

**Comment by DG12** [comment]
OK

**Comment by DG12** [comment]
This and #99 are resolved with update of main.c 8/1/18
