### ISSUE TITLE
Mode (raw/URL) must be saved so reset doesn't reset to default

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvitag_fw#106]
Tags have been known to spontaneously reset. This causes the tag to return to the mode (raw/URL) of of the initial configuration.
__
Suggest saving mode in "UICR — User information configuration registers .. non-volatile memory"
CUSTOMER[0] 0x080 ( first 32 bit register of 32 registers) Reserved for customer 

Erased bits are one. Bits can only be written as zero making changing the mode back  (or other configuration item to a different value) awkward.

A crazy scheme for an item having a single bit value would be use an entire CUSTOMER register for one item,  start with an item value of zero and toggle it for each zero in the CUSTOMER register. For example 
a CUSTOMER register value of
`0000 1111 1111   1111 1111   1111 1111 `
would specify 4 toggles of the initial value resulting in a zero !
This would allow 32 changes before needing ERASEUICR (Make up your mind already whether you want raw or you want URL!)

Perhaps a really crazy scheme for items requiring 2 or more bits to define their value, of using an entire CUSTOMER register (or more) for a configuration item where bits are grouped with a leading "INUSE" 0 followed by the value could be used. For example for a two bit item (values 0,1,2,3 ) the first time it is set CUSTOMER[0} would be:
`0vv1 1111   1111 1111   1111 1111   1111 1111 `
Examining the bits in 3-bit-groups  (from the left), the first group has the INUSE indicator a 0 specifying  that vv is the value. The next group (with the INUSE indicator of a 1 ) specifies that the second group (and all subsequent groups ) are not in use.

When the value is changed the result would be 
`0??0 ww11   1111 1111   1111 1111   1111 1111` .
examining the bits in groups, the second group has a zero indicating it is INUSE and the value for the item is ww.
This would allow 10 changes (using only one CUSTOMER register ) before needing ERASEUICR 

NVMC must be enabled for writing in CONFIG.WEN
See nRF52832 Product Specification V1.3, section 11 for details .
See API for proper function calls (I will add another section when I research that.

**Comment by ojousima** [comment]
This feature has been on our TODO longer than I care to admit 😄 

I think UICR is not erasable during run time, [but only while flashing](https://devzone.nordicsemi.com/f/nordic-q-a/11781/writing-to-uicr-from-application-code). Please correct me if I'm wrong, maybe link to a devzone post or relevant code snippet?

Storing setup of the tag is definitely required by the time tags are configurable at runtime. I'm not 100% sure if the feature will be implemented in 2.X versions which are built on top of SDK12.3 or maybe in 3.X versions which will be built on top of SDK 14. 

I'll leave this one open as "help wanted", if some kind soul implements it and opens a pull request I'd be happy to merge the feature.

**Comment by DG12** [comment]
Seems that UICR and other flash are independent.
 ERASEUICR is independent of ERASEPAGE  (of flash)
 however ERASEALL erases both.
Additional info:
See nRF52832 Product Specification V1.3, section  
11.3 Writing to user information configuration registers
14.1.28 CUSTOMER[0]  Address offset: 080 ,,,[31] 0FC

PS if the issue was worded "mode status lost during spontaneous reset" it could considered BUG 😄

**Comment by ojousima** [comment]
Done in e3785f004ffbf623d145944d3f4f62b88780a26e
