### ISSUE TITLE
Boot loader main must cripple WatchDogTimer

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvitag_fw#110]
WatchDogTimer reset: 

Althouh per nRF52832 Product Specification V1.3  "18 POWER section" "18.8 Reset behavior" "the WDT is not retained at pin reset, Brownout reset and Power on reset". If the watchdog timer is started by the target application it will continue running after a softreset. This includes during the MBR,  the boot loader process when the ruuvi tag is determining whether it should run the application or when the "B" button is depressed to enter the DFU(Device Firmware Update) mode. In addition WDT may expire during DFU. 
This causes the DFU to sometimes be aborted when the WDT expires.

Although it would be best if the MBR  crippled the WDT, at least the ruuvi boot loader should.

Section 40.3 Watchdog reset states that ..." after a reset, or waking up from OFF mode, the watchdog
configuration registers will be available for configuration... 

WDT  INTENCLR should also be SET to "Disable interrupt for TIMEOUT event"

See discussion and Nordic response at 
[WDT large value](https://devzone.nordicsemi.com/f/nordic-q-a/26182/what-if-watchdog-reload-value-is-long-enough-for-dfu/103123#103123)
[WDT after SoftReset](https://devzone.nordicsemi.com/f/nordic-q-a/27590/use-initialized-wdt-after-software-reset-on-a-nrf52)

**Comment by ojousima** [comment]
On a quick look it seems that bootloader in SDK15 feeds the watchdog. Therefore I'm marking this as wontfix here, and this issue will be resolved when we port to SDK15 (although this is far in future)

**Comment by DG12** [comment]
Seems a simple enough fix affecting all tags distributed so fan and into the "far  future" not sure why you set to wont fix .
