### ISSUE TITLE
Synchoronize ADC reads to radio activity

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvitag_fw#140]
Battery voltage droops during radio activity. Synchronize ADC to radio to get more realistic estimate of the remaining battery capacity

**Comment by DG12** [comment]
Please review my suggestion in slack of 12/7 regarding using PFCON / POFWARN to eliminate use of ADC altogether.

**Comment by ojousima** [comment]
Suggestion has been reviewed, and maybe it'll be added later on. For now the ADC will be used as it will give some insight on remaining capacity, even if it's not perfect.

**Comment by ojousima** [comment]
Done in f47e436bfe5ac48cad1b5812eba40fc9ae1fabff
