### ISSUE TITLE
dig_H6 is signed

### ISSUE THREAD

**Issue by wassfila** [ruuvi/ruuvitag_fw#16]
A free code review from a friend project https://wassfila.github.io/ shows this issue with signed unsigned:
in your data structure you have
uint8_t  dig_H6;
in the datasheet Page 23, dig_H6 is mentionned as a signed char.

I would not want to be debugging the impact that would have, a change should also be tested, I do not have your platform, I wish I had one, not available yet I think. So I let you care of this fix.

**Comment by ojousima** [comment]
Thank you for the report @wassfila , fixed in https://github.com/ruuvi/ruuvitag_fw/pull/17
