### ISSUE TITLE
DFU Binaries are not up to date - update

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvitag_fw#21]

**Comment by ojousima** [comment]
weathre station updated, bootloaders are ok as is. Check test-drivers and ble-beacon

**Comment by aliverud** [comment]
Hi, I have tried to upload the weather station dfu image using nRF Toolbox for Android to my ruuvitag device.
However, after approximately 35 seconds the application reports:
Upload Failed, DFU Device Disconnected
The same happends for ble_app_beacon.zip.

Any suggestions?

**Comment by ojousima** [comment]
Please navigate to lab.ruuvi.com for oifficial builds, and keep an eye on github releases here. "Builds" folder will eventually be deleted

**Comment by ojousima** [comment]
Up-to-date binaries are in a release, closing.
