### ISSUE TITLE
Nrf connect not finding ruuvitag on Android 4.4.4 

### ISSUE THREAD

**Issue by jsavage** [ruuvi/ruuvitag_fw#36]
I am hoping this is the right place to raise this but I am wondering if RuuviTag firmware is configured and  compiled to be compatible with Android 4.4.4. 
The issue I am facing is that I cannot use nrf connect to DFU a ruuvitag on my Android 4.4.4 smartphone.  I am not sure what SDK has been used but the symptoms seem similar to  https://stackoverflow.com/questions/43992519/android-4-4-4-can-not-connect-to-nordic-semi-sdk-13-devices

**Comment by ojousima** [comment]
We're using SDK 12.3. There have been similar reports with Android 7 devices, notably Samsung Galaxy S8. Nordic has been notified of the issue. In meanwhile, please try using nRF Toolbox DFU app.
