### ISSUE TITLE
Enable GPIO high (current) drive for LED pins

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvitag_fw#4]
To drive LEDs safely with more than 0.5mA current, high drive option should be enabled (for LED pins). High drive needs to be enabled on both, bootloader and FW.

http://infocenter.nordicsemi.com/topic/nrf52.v1.7/Chunk1498869550.html?cp=1_1_0_16_3_0#unique_1435213149

**Comment by ojousima** [comment]
Moving this issue as task to trello, https://trello.com/c/tTjfWuW9. This issue will be closed on Github when the fix has been implemented.

**Comment by ojousima** [comment]
Bootloader has high current drive enabled. I'd prefer to not enable high current drive on programs, as the difference in current consumption (2 mA vs 8 mA) is quite large and I've not noticed any adverse effects in driving LEDs with lower current. @laurijamsa comments?

**Comment by laurijamsa** [comment]
Since we also increased LEDs' series resistors from 470ohm to 1kohm, this should not be required anymore. If VDD = 3.3V and Vf of the LED 1.7V -> I=1.6mA (which should be safe to drive without high drive option). Maybe that 0.5mA was incorrect (link is broken now)?

**Comment by ojousima** [comment]
Electrical specification says 1-4 mA (min / max) now.
![https://infocenter.nordicsemi.com/topic/com.nordic.infocenter.nrf52832.ps.v1.1/gpio.html?cp=2_2_0_19_3#unique_522553113](https://cloud.githubusercontent.com/assets/2360368/21581394/90d1b6c2-d039-11e6-89bc-76ecd3724c90.png)

Considering increased series resistance and that current specification is referred to voltage at pin (VSS + 0.4 V), I think the current drive can be left at "standard". Closing the issue.
