### ISSUE TITLE
Missing template_application in sdk12 distribution_packages

### ISSUE THREAD

**Issue by mdxs** [ruuvi/ruuvitag_fw#46]
The README of the sdk12 distribution_packages mentions a `template_application`, that:

> initializes sensors and waits a minute for the user to press button. If user presses button during that minute, application enters main loop, otherwise the application will shut down to preserve battery.

But there doesn't seem to be such a `template_application.zip`.

**Comment by ojousima** [comment]
Yes, the template application is somewhat historic. Generally people just use Ruuvi Firmware as a template. I removed the builds folder to avoid confusion, please use "releases" for up-to-date and tested binaries

**Comment by mdxs** [comment]
Clear, that is indeed better.
