### ISSUE TITLE
Improving documentation to build on Linux

### ISSUE THREAD

**Issue by mdxs** [ruuvi/ruuvitag_fw#50]
The `README.md` file provides some instructions to build on Linux, these however are not clear enough to complete the task in my opinion.

In particular the `Prerequisites (to compile)` section provides some advise that doesn't seem to work (at least not on my clean environment based on Xubuntu 16.04.3). The information on using the official GNU ARM Embedded PPA on Ubuntu doesn't seem to provide a working toolchain. It seems to provide a way to modern/up-to-date toolchain, which doesn't seem to work with the current nRF52 SDK12 used in the project. While this is an alternative, I suggest to remove it altogether (and plan to submit a PR to do so); as it doesn't seem to provide a toolchain that allows to build the `ruuvitag_fw` project.

Furthermore, the main suggestion to "Download and install GCC" doesn't clarify which version to download and install; and seems to miss some other relevant information. Online resources suggest that the nRF52 SDK12 and in particular the 12.3.0 require version 4.9.3 of the GNU ARM Embedded toolchain. For which some installation instructions can be found at https://github.com/thingsee/thingsee-sdk/wiki/GNU-ARM-Embedded-Toolchain - though some small modifications to those instructions work even smoother for this `ruuvitag_fw` project (and I plan to submit a PR to provide those instructions).

**Comment by ojousima** [comment]
Thank you for all the work you've put in to clarify the documentation, we'll wait for the PR
