### ISSUE TITLE
Tailoring values belong in a separate header file

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvitag_fw#74]
Currently several "tailorable" values are in various files and directories.
Including:
HUMIDITY_OVERSAMPLING, TEMP_OVERSAMPLING, PRESSURE_OVERSAMPLING,
BME280_IIR, BME280_STANDBY_MS, BATTERY_POLLING_INTERVAL (not 30), MAIN_LOOP_INTERVAL_URL(remove the divide by 10), MAIN_LOOP_INTERVAL_HIGHRES, INITIAL_MODE, LIS2DH12_RATE_HIGHRES, LIS2DH12_RATE_URL, XMIT_LEVEL, URL_DOMAIN,  URL_BASE_LENGTH

Placing them all in a single header file would allow tailoring without modifying assorted files in various directories.

**Comment by ojousima** [comment]
Fixed in #c4998b60a605d4622b00af5260d8c6e9156ee11c, closing
