### ISSUE TITLE
V1-backports RuuviFW 1.2.5: URL Beacon ID is NAN on ruu.vi site 

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvitag_fw#93]

**Comment by ojousima** [comment]
This is caused by addition of "/" to ruu.vi URL, which bumps the ID char away. the "/" is required for some browsers.

Possible solutions: 
* Return to URL format 2
* Use ruuvi.com/, and replace .com/ with Eddystone shorthand to save one character.

@laurijamsa

**Comment by Scrin** [comment]
Another possible solution is to remove the # from the url to save one character, though doing this will actually send the measurement to the server too as part of the request (the fragment identifier is not sent by the browser), and thus the page cannot be cached for changing measurements.

**Comment by DG12** [comment]
@Scrin I previously proposed a complete solution which handles the  removal of the fragment identifier at weather-station-serverside
